"""Initial migration.

Revision ID: 231f64c2e825
Revises: 
Create Date: 2022-04-19 10:58:05.488189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231f64c2e825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('biography', sa.Text(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'biography')
    # ### end Alembic commands ###
